fullnameOverride: ${release_name}
controller:
  serviceAccount:
    name: ${sa_name}
    create: true
    annotations:
      eks.amazonaws.com/role-arn: ${irsa_role}
%{ if has_dedicated_infra_nodes }
  nodeSelector:
    role: infra
%{ endif }
storageClasses:
 - name: ebs-sc
   annotations:
     storageclass.kubernetes.io/is-default-class: "true"
   volumeBindingMode: WaitForFirstConsumer
   reclaimPolicy: Delete
   allowVolumeExpansion: true
   parameters:
     encrypted: "true"
